name: "Déploiement sur le serveur cible"
author: "Alain Guillon"
branding:
  color: purple
  icon: box
description: "Effectue une déploiement sur le serveur cible"
inputs:
  vps_key:
    description: "Clé ssh pour le VPS"
    required: true
  server_ip:
    description: "Adresse IP du serveur cible"
    required: true
  token_github:
    description: "Token Github"
    required: true
  user_vps:
    description: "Utilisateur pour la connexion ssh sur le serveur"
    default: root
runs:
  using: composite
  steps:
    - name: Déployer sur le serveur
      shell: bash
      run: |
        eval $(ssh-agent -s)
        ssh-add - <<< "${{ inputs.vps_key }}"
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ inputs.server_ip }} >> ~/.ssh/known_hosts
        scp docker-compose.production.yml ${{ inputs.user_vps }}@${{ inputs.server_ip }}:/root/docker-compose.production.yml
        ssh ${{ inputs.user_vps }}@${{ inputs.server_ip }} "docker login ghcr.io -u ${{ github.actor }}" -p ${{ inputs.token_github }}
        ssh ${{ inputs.user_vps }}@${{ inputs.server_ip }} "docker compose -f /root/docker-compose.production.yml up -d --force-recreate"
