name: CI-CD

on:
    push:
        branches:
            - main

jobs:
    # Connexion sur Github Container Registry
    login:
        runs-on: ubuntu-latest
        steps:
            - name: Connexion au Github Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
